import { NextPage } from "next";
import Head from "next/head";
import { BackgroundWrapper } from "../components/BackgroundWrapper";
import { BlogCard } from "../components/BlogCard";
import { Header } from "../components/Header";

const Blog: NextPage = () => {
  return (
    <BackgroundWrapper>
      <Head>
        <title>Blog | DogeDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <Header headerTitle="Blog" />

      <BlogCard />
    </BackgroundWrapper>
  );
};

export default Blog;
