import type { NextPage } from "next";
import usePersistedState from "../utils/usePersistedState";

import Head from "next/head";
import Image from "next/image";
import { Container } from "../styles/home";
import { Header } from "../components/Header";
import { ProfileInfo } from "../components/ProfileInfo";

import GlobalStyle from "../styles/global";
import { ThemeProvider, DefaultTheme } from "styled-components";
import light from "../styles/themes/light";
import dark from "../styles/themes/dark";

const Home: NextPage = () => {
  const [theme, setTheme] = usePersistedState<DefaultTheme>("theme", light);

  const toggleTheme = () => {
    setTheme(theme.title === "light" ? dark : light);
  };

  return (
    <ThemeProvider theme={theme}>
      <Container>
        <Head>
          <title>Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/icons/favicon.ico" />
        </Head>
        <GlobalStyle />

        <Header toggleTheme={toggleTheme} />
        <ProfileInfo />
      </Container>
    </ThemeProvider>
  );
};

export default Home;
