import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { Header } from "../components/Header";
import { ProfileInfo } from "../components/ProfileInfo";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>

      <Header />
      <ProfileInfo />
    </div>
  );
};

export default Home;
